# FeatherSpawner Config

approved-silk-touch-tools:
  - WOODEN_PICKAXE
  - STONE_PICKAXE
  - IRON_PICKAXE
  - GOLDEN_PICKAXE
  - DIAMOND_PICKAXE
  - NETHERITE_PICKAXE

settable-spawners:
  - ZOMBIE
  - SKELETON
  - SPIDER
  - CAVE_SPIDER
  - SILVERFISH
  - BLAZE
  - MAGMA_CUBE
