name: FeatherSpawners
version: '${project.version}'
main: net.zerek.featherspawners.FeatherSpawners
api-version: 1.19
authors: [ Zerek ]
description: Allows for picking up spawners with silktouch and changing spawners with commands
